language: node_js
node_js:
- '4'
- '6'
cache:
  directories:
  - node_modules
script:
- npm run test
branches:
  except:
  - "/^build-[0-9a-z\\-]*/"
notifications:
  slack:
    secure: L72c2eUbeBM5iaMTfxg9jx2nSQNjWxoBHhjT16whyakQZ1C0JqymtLC2y3MoiOoi59cT6WGa0X9jUdKhvygrUccJAmKlEfSUM60pCXBasXd6UHnbu/fBUXuGCumHGzm/VbsEaLGoMw3OUK8J+yxrYQtl4Zd6vfeaLy7Xq76Wkt5imwTyYCQ61wMbKkvXFIqCdTOZAxd4CSBVLf809tg3ULX5DgF6FjxO8R8uSUdztzFBwD2oAylLOZA0QbfiU7Fd0xYI+i3huxNSSSE8sT8ZpZ9YkHkJ4ChF6uQtWfGm2t+v0xwVCdBwIqyiCaZ+nlIC+a6nD19a4iBKyR47nE3TJh8YODBbvC/sVmY4TOLfIah+brGYUCUIMTPFAF7u7keyOqfZWM7JCJM6257rZfHewXr8NR7I2TEAdLAzEpDTpvSqcebNmGG4P3mJdaDaa2tTJtszZT3QFFb1qRkQ08yqRANlOGHRDRlzI5ucxGshTtx/OH295Te7FQzKb3k7mq90jT/lkRrPlySgejPCgUllkTtVG3pgPxbW1Yclgw5ImgyhSqEr1NrPIc1dH/7izxGYA3Y9oeZ1G7C/Vm2EsKnsr7E+R3LAGQcyHWc8m1SMG6CLAgS7u9lOLXEEAdsL2OIMerC9qksoIHmkYBdb8e84wQCZu+K/6OHPff8jbKg0/gs=
deploy:
  provider: npm
  email: 'acastofthousands@gmail.com'
  api_key:
    secure: PvBxRxa2gch1yQZ5/NIywbmCMfVxRYydON+3hDBjbwWboZDaVs4YA4+M0AD+tuvY50lJrjByqObuT7XBUIOS8SrBgEi2RSNX2JzH0rQla4oaM/s+lSv+P2TVrpAA7Tzf4kVROOQjOYAOUkBNq2sQh7TncM2F58YMg3pyD0t7Yix9FSwwMXESKKaNPYD14slMtdcnpACyGPkZheZ37jDUE8GAK7qrrG4tdoXlDkgtsMT5Nfp6k2YIvW+q75XgD/v/I7swD4j29byanaaEntumzTz0M22CtgmZvSbVrSwyZNlxqB3SE8wJS6XKPh7TQYEcDIvj+/ltpoLwy2fBiO/pl7kB650Fge1XHX9aD8fuu4j2Rcj8Z4CxWfwh9OTRKDhgkK+t8q9I4IsvIoZf+NH95olWgMEijmGL8Q+z5d6a4d+ADTiv6SmnBdTDss3aj3SGJH0vGHPk/JHoRDNu4NNPAW2zT/VCxIbDJREUP4ScfhbC1cO/7Zl8602LYab6kl/bxYmo8ClE8/IXwe7zwbPSMo7J44Px0FRAY2azZlmzo2QITN32IbkGgFqxVFHKbjAukVQIVjbQosmlovZQu8H0OEBh2PIsk9N7Mj05CcMviQcECmot33RMXKVf9DvD4LXcwoseiCszpUg3DTLBjQQQ+pitFvmbmDjkGG41QkLAiAA=
  on:
    tags: true
    repo: UKHomeOffice/evw-validation-rules
